apiVersion: v1
kind: Secret
metadata:
  name: pgpool
  namespace: mcc
data:
  PGPOOL_SR_CHECK_USER: cmVwbWdy
  PGPOOL_SR_CHECK_PASSWORD: cmVwQG1ncg==
  PGPOOL_POSTGRES_USERNAME: cG9zdGdyZXM=
  PGPOOL_POSTGRES_PASSWORD: cGdAYWRtaW4=
  PGPOOL_POSTGRES_CUSTOM_USERS: bWNjdXNlcg==
  PGPOOL_POSTGRES_CUSTOM_PASSWORDS: bWNjQDEzNTc5
  PGPOOL_ADMIN_USERNAME: YWRtaW4=
  PGPOOL_ADMIN_PASSWORD: cHdwZ2FkbQ==
