apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: mcc
data:
  POSTGRESQL_POSTGRES_PASSWORD: cGdAYWRtaW4=
  POSTGRESQL_USERNAME: bWNjdXNlcg==
  POSTGRESQL_PASSWORD: bWNjQDEzNTc5
  REPMGR_USERNAME: cmVwbWdy
  REPMGR_PASSWORD: cmVwQG1ncg==
